
services:
  app:
    build: .
    container_name: airport_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  # mysql_db:
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 5s
  #     timeout: 10s
  #     retries: 10
  #   image: mysql:8.0
  #   container_name: mysql_container
  #   env_file:
  #     - .env
      
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # volumes:
  #   mysql_data: 

